package cli

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/spf13/cobra"

	"github.com/dimetron/pi-go/internal/memory"
)

func newMemoryRecentCmd() *cobra.Command {
	var (
		flagLimit int
		flagType  string
		flagJSON  bool
	)

	cmd := &cobra.Command{
		Use:   "recent [project]",
		Short: "Show recent memory observations",
		Long: `Displays recent observations and session summaries stored in the memory system.

Shows compressed observations (tool call summaries) and session summaries (end-of-session
summaries generated by the LLM). By default, uses the current working directory as the
project. Use --limit to control how many observations to show (default 20).

Examples:
  pi memory recent                     # recent memories from current project
  pi memory recent ~/code/myapp       # recent memories from specific project
  pi memory recent --limit 50          # show more entries
  pi memory recent --type discovery    # filter by type (decision, bugfix, feature, refactor, discovery, change)
  pi memory recent --json              # output as JSON`,
		RunE: func(cmd *cobra.Command, args []string) error {
			project := ""
			if len(args) > 0 {
				project = args[0]
			}
			return runMemoryRecent(project, flagLimit, flagType, flagJSON)
		},
	}

	cmd.Flags().IntVar(&flagLimit, "limit", 20, "Maximum observations to show")
	cmd.Flags().StringVar(&flagType, "type", "", "Filter by observation type")
	cmd.Flags().BoolVar(&flagJSON, "json", false, "Output as JSON")

	return cmd
}

func runMemoryRecent(project string, limit int, obsType string, asJSON bool) error {
	// Resolve project: use provided path, current directory, or error.
	if project == "" {
		cwd, err := os.Getwd()
		if err != nil {
			return fmt.Errorf("getting working directory: %w", err)
		}
		project = cwd
	}

	// Find the memory database.
	dbPath, err := findMemoryDB(project)
	if err != nil {
		return err
	}

	memDB, err := memory.OpenDB(dbPath)
	if err != nil {
		return fmt.Errorf("opening memory database: %w", err)
	}
	defer memDB.Close()

	store := memory.NewSQLiteStore(memDB)
	ctx := context.Background()

	// Validate type filter if provided.
	if obsType != "" {
		if !memory.ValidObservationTypes[memory.ObservationType(obsType)] {
			return fmt.Errorf("invalid type %q, valid types: decision, bugfix, feature, refactor, discovery, change", obsType)
		}
	}

	// Fetch recent observations.
	observations, err := store.RecentObservations(ctx, project, limit*2) // fetch extra for filtering
	if err != nil {
		return fmt.Errorf("fetching recent observations: %w", err)
	}

	// Filter by type if specified.
	if obsType != "" {
		filtered := make([]*memory.Observation, 0, len(observations))
		for _, obs := range observations {
			if string(obs.Type) == obsType {
				filtered = append(filtered, obs)
				if len(filtered) >= limit {
					break
				}
			}
		}
		observations = filtered
	} else if len(observations) > limit {
		observations = observations[:limit]
	}

	// Also fetch session summaries.
	summaries, err := store.RecentSummaries(ctx, project, limit)
	if err != nil {
		return fmt.Errorf("fetching recent summaries: %w", err)
	}

	if asJSON {
		return printRecentJSON(observations, summaries, limit)
	}

	if len(observations) == 0 && len(summaries) == 0 {
		fmt.Println("No observations found.")
		fmt.Printf("Project: %s\n", project)
		return nil
	}

	fmt.Printf("Recent Memory — %s\n", project)
	fmt.Println()

	// Show observations.
	if len(observations) > 0 {
		fmt.Printf("Observations (%d)\n", len(observations))
		fmt.Println("────────────")
		for _, obs := range observations {
			age := formatAge(obs.CreatedAt)
			fmt.Printf("[%s] %-12s %s\n", age, obs.Type, obs.Title)
		}
		fmt.Println()
	}

	// Show session summaries.
	if len(summaries) > 0 {
		fmt.Printf("Session Summaries (%d)\n", len(summaries))
		fmt.Println("──────────────────")
		for _, sum := range summaries {
			age := formatAge(sum.CreatedAt)
			request := sum.Request
			if len(request) > 80 {
				request = request[:80] + "..."
			}
			fmt.Printf("[%s] %s\n", age, request)
		}
	}

	return nil
}

// findMemoryDB locates the memory database, checking project-specific and global locations.
func findMemoryDB(project string) (string, error) {
	// Try project-specific path first.
	if project != "" {
		projectDB := filepath.Join(project, ".pi-go", "memory", "claude-mem.db")
		if _, err := os.Stat(projectDB); err == nil {
			return projectDB, nil
		}
		// Also try palace legacy location.
		palaceDB := filepath.Join(project, ".pi-go", "palace.db")
		if _, err := os.Stat(palaceDB); err == nil {
			return palaceDB, nil
		}
	}

	// Try global path (~/.pi-go/memory/claude-mem.db).
	home, err := os.UserHomeDir()
	if err == nil {
		globalDB := filepath.Join(home, ".pi-go", "memory", "claude-mem.db")
		if _, err := os.Stat(globalDB); err == nil {
			return globalDB, nil
		}
	}

	return "", fmt.Errorf("memory database not found")
}

func formatAge(t time.Time) string {
	age := time.Since(t)
	switch {
	case age < time.Minute:
		return "just now"
	case age < time.Hour:
		mins := int(age.Minutes())
		return fmt.Sprintf("%dm ago", mins)
	case age < 24*time.Hour:
		hours := int(age.Hours())
		return fmt.Sprintf("%dh ago", hours)
	case age < 7*24*time.Hour:
		days := int(age.Hours() / 24)
		return fmt.Sprintf("%dd ago", days)
	default:
		return t.Format("Jan 2")
	}
}

// printRecentJSON outputs the results as JSON.
func printRecentJSON(observations []*memory.Observation, summaries []*memory.SessionSummary, limit int) error {
	type recentOutput struct {
		Observations []*memory.Observation    `json:"observations"`
		Summaries    []*memory.SessionSummary `json:"summaries"`
		Limit        int                      `json:"limit"`
	}
	out := recentOutput{
		Observations: observations,
		Summaries:    summaries,
		Limit:        limit,
	}
	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	return enc.Encode(out)
}
