package provider

import (
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// withTempCacheDir points the user cache dir at a temp dir for the duration of
// the test and returns the pi-go models cache path.
func withTempCacheDir(t *testing.T) string {
	t.Helper()
	home := t.TempDir()
	t.Setenv("HOME", home)
	// os.UserCacheDir on macOS is $HOME/Library/Caches; on Linux it honors
	// XDG_CACHE_HOME. Point both at the temp home so the test is portable.
	t.Setenv("XDG_CACHE_HOME", filepath.Join(home, ".cache"))
	return modelsCacheDir()
}

func TestRefreshCatalogWritesCache(t *testing.T) {
	cacheDir := withTempCacheDir(t)
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		_ = json.NewEncoder(w).Encode(map[string]any{
			"data": []map[string]any{
				{
					"id":                 "mistral-large-latest",
					"owned_by":           "mistral",
					"max_context_length": 128000,
					"capabilities": map[string]any{
						"completion_chat": true,
					},
				},
			},
		})
	}))
	defer srv.Close()

	models, err := RefreshCatalog(context.Background(), "mistral", ListModelsOptions{BaseURL: srv.URL})
	if err != nil {
		t.Fatalf("RefreshCatalog: %v", err)
	}
	if len(models) != 1 || models[0].ID != "mistral-large-latest" {
		t.Fatalf("models = %+v", models)
	}
	// Cache file written and valid JSON.
	b, err := os.ReadFile(filepath.Join(cacheDir, "mistral.json"))
	if err != nil {
		t.Fatalf("cache file: %v", err)
	}
	var cf catalogFile
	if err := json.Unmarshal(b, &cf); err != nil {
		t.Fatalf("cache file not valid JSON: %v", err)
	}
	if cf.Provider != "mistral" || len(cf.Models) != 1 {
		t.Errorf("cache file = %+v", cf)
	}
	// CatalogFor now returns the fetched ID.
	ids := CatalogFor("mistral")
	if !contains(ids, "mistral-large-latest") {
		t.Errorf("CatalogFor(mistral) = %v, want fetched ID", ids)
	}
}

func TestCatalogForNoCacheFallsBackToEmbedded(t *testing.T) {
	withTempCacheDir(t)
	ids := CatalogFor("mistral")
	if len(ids) == 0 {
		t.Fatal("CatalogFor(mistral) empty, want embedded snapshot")
	}
	if !contains(ids, "mistral-large-latest") {
		t.Errorf("embedded snapshot missing mistral-large-latest: %v", ids)
	}
}

func TestCatalogForCacheModelNotInEmbedded(t *testing.T) {
	cacheDir := withTempCacheDir(t)
	cf := catalogFile{
		Provider:  "mistral",
		FetchedAt: "2026-08-27T00:00:00Z",
		Models:    []ModelInfo{{ID: "codestral-2508"}},
	}
	b, _ := json.Marshal(cf)
	if err := os.MkdirAll(cacheDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(cacheDir, "mistral.json"), b, 0o644); err != nil {
		t.Fatal(err)
	}
	ids := CatalogFor("mistral")
	if !contains(ids, "codestral-2508") {
		t.Errorf("CatalogFor(mistral) = %v, want cached codestral-2508", ids)
	}
}

func TestCatalogForInvalidCacheFallsBack(t *testing.T) {
	cacheDir := withTempCacheDir(t)
	if err := os.MkdirAll(cacheDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(cacheDir, "mistral.json"), []byte("not json"), 0o644); err != nil {
		t.Fatal(err)
	}
	ids := CatalogFor("mistral")
	if len(ids) == 0 {
		t.Fatal("CatalogFor(mistral) empty after invalid cache, want embedded fallback")
	}
}

func TestCatalogForPrefersEmbeddedSnapshot(t *testing.T) {
	// With no XDG cache, CatalogFor should prefer the checked-in
	// modeldata/models-mistral.json snapshot over the hard-coded list when the
	// snapshot exists. The snapshot is not committed in this PR (it is
	// generated by `make fetch-models`), so this asserts the fallback path
	// still returns the hard-coded list.
	withTempCacheDir(t)
	ids := CatalogFor("mistral")
	if len(ids) == 0 {
		t.Fatal("CatalogFor(mistral) empty")
	}
	if !contains(ids, "mistral-large-latest") {
		t.Errorf("CatalogFor(mistral) missing mistral-large-latest: %v", ids)
	}
}

func TestRefreshCatalogErrorLeavesCacheIntact(t *testing.T) {
	cacheDir := withTempCacheDir(t)
	// Seed a valid cache file.
	cf := catalogFile{
		Provider:  "mistral",
		FetchedAt: "2026-08-27T00:00:00Z",
		Models:    []ModelInfo{{ID: "mistral-large-latest"}},
	}
	b, _ := json.Marshal(cf)
	if err := os.MkdirAll(cacheDir, 0o755); err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(cacheDir, "mistral.json")
	if err := os.WriteFile(path, b, 0o644); err != nil {
		t.Fatal(err)
	}

	// Fetch fails (server 500).
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusInternalServerError)
	}))
	defer srv.Close()

	_, err := RefreshCatalog(context.Background(), "mistral", ListModelsOptions{BaseURL: srv.URL})
	if err == nil {
		t.Fatal("expected error from failed fetch")
	}
	// Prior cache file intact.
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("cache file gone after failed refresh: %v", err)
	}
	if !strings.Contains(string(got), "mistral-large-latest") {
		t.Errorf("cache file changed after failed refresh: %s", got)
	}
}

func contains(ss []string, want string) bool {
	for _, s := range ss {
		if s == want {
			return true
		}
	}
	return false
}
